#!/bin/sh

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "\033[1;93m  _____         _______ _     _\n |_____] |      |______  \\___/ \n |       |_____ |______ _/   \\_\n $DISTRIB_DESCRIPTION\n\n\033[0m"
